mj:
  discord:
    guild-id: 1118933179361935523
    channel-id: 1118933179361935526
#    user-token: ODg4MDM3Nzg2NDMzNzU3MjU1.G_Cl-Y.SfGJTnW8IomvRr6UQA9NfOCtnvORoVfcI5_lHU
    user-token: ODg4MDM3Nzg2NDMzNzU3MjU1.G-uScI.j5s5KH3P5f3S98JkT3UDt85SwvtwZpTXkn34go
    session-id: b1cbde91c14b87c66ccd3b3dc65c7b62
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
    user-wss: true
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  queue:
    timeout-minutes: 5
    core-size: 3
    queue-size: 10